### ISSUE TITLE
KeyError: 'FastBEV is not in the models registry'

### ISSUE THREAD

**Issue by LiuXuan66** [Mandylove1993/CUDA-FastBEV#14]
When I run python3 ptq/dump-data.py. 
mmcv-full-1.4.0
mmdet3d-0.15.0
torch-1.5.1
mmdet-2.25.1
Traceback (most recent call last):
  File "ptq/dump-data.py", line 165, in <module>
    dump_tensor(args)
  File "ptq/dump-data.py", line 108, in dump_tensor
    model = init_model(args.config, args.checkpoint, device=args.device)
  File "/home/liu/.local/lib/python3.8/site-packages/mmdet3d/apis/inference.py", line 57, in init_model
    model = build_model(config.model, test_cfg=config.get('test_cfg'))
  File "/home/liu/.local/lib/python3.8/site-packages/mmdet3d/models/builder.py", line 83, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/home/liu/.local/lib/python3.8/site-packages/mmdet3d/models/builder.py", line 56, in build_detector
    return DETECTORS.build(
  File "/home/liu/.local/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/liu/.local/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/liu/.local/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'FastBEV is not in the models registry'

**Comment by LiuXuan66** [comment]
Got it! Thanks!

**Comment by DWendou** [comment]
> Got it! Thanks!

怎么解决的？
